# Generated by Django 3.2.5 on 2021-07-12 10:35

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Post_image/')),
            ],
        ),
    ]
