# Generated by Django 3.2.5 on 2021-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210714_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='com_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
