# Generated by Django 3.2.5 on 2021-07-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_post_com_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='com_count',
            new_name='user_count',
        ),
    ]
