# Generated by Django 3.2.5 on 2021-07-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_com_count_post_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_count',
        ),
    ]
