# Generated by Django 3.2.5 on 2021-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_post_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no',
            field=models.IntegerField(default=1),
        ),
    ]
